// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Swintake.domain.Data;

namespace Swintake.domain.Migrations
{
    [DbContext(typeof(SwintakeContext))]
    [Migration("20181220120817_InitialSetupDatabase")]
    partial class InitialSetupDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Swintake.domain.Campaigns.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ClassStartDate");

                    b.Property<string>("Client")
                        .HasMaxLength(60);

                    b.Property<string>("Comment")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .HasMaxLength(60);

                    b.Property<DateTime>("StartDate");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");

                    b.HasData(
                        new { Id = new Guid("f024fe5d-c994-48df-8849-1eb513049b71"), ClassStartDate = new DateTime(2019, 2, 20, 13, 8, 16, 281, DateTimeKind.Local), Client = "mixed", Comment = "max 8 candidates", Name = "dotnet class 2019", StartDate = new DateTime(2019, 1, 20, 13, 8, 16, 283, DateTimeKind.Local), Status = 1 },
                        new { Id = new Guid("717d8747-dc4f-4655-99f4-ec936a4afbc4"), ClassStartDate = new DateTime(2018, 12, 20, 13, 8, 16, 286, DateTimeKind.Local), Client = "CM", Comment = "at cm location", Name = "Java academy 2019", StartDate = new DateTime(2018, 12, 20, 13, 8, 16, 286, DateTimeKind.Local), Status = 1 },
                        new { Id = new Guid("d5c5b85d-feb7-4f4a-b60a-f09525bd0553"), ClassStartDate = new DateTime(2019, 2, 8, 13, 8, 16, 286, DateTimeKind.Local), Client = "open for all", Comment = "", Name = "Short javascript bootcamp", StartDate = new DateTime(2018, 12, 30, 13, 8, 16, 286, DateTimeKind.Local), Status = 1 }
                    );
                });

            modelBuilder.Entity("Swintake.domain.Candidates.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment")
                        .HasMaxLength(500);

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .HasMaxLength(60);

                    b.Property<string>("GitHubUsername")
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .HasMaxLength(60);

                    b.Property<string>("LinkedIn")
                        .HasMaxLength(200);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Candidates");

                    b.HasData(
                        new { Id = new Guid("78688585-ea60-413a-bfff-e4ede781200b"), Comment = "", Email = "gwen.jamroziak@cegeka.com", FirstName = "Gwen", GitHubUsername = "gwenjamroziak", LastName = "Jamroziak", LinkedIn = "gwenjamroziak", PhoneNumber = "0472020406" },
                        new { Id = new Guid("054d5899-a803-499e-b5cb-ea2fe1a99b6c"), Comment = "", Email = "caroline.callens@cegeka.com", FirstName = "Caroline", GitHubUsername = "carolinecallens", LastName = "Callens", LinkedIn = "carolinecallens", PhoneNumber = "0472030507" },
                        new { Id = new Guid("d4ebff88-7319-453a-849d-a0f726748432"), Comment = "", Email = "siene.dekeyser@cegeka.com", FirstName = "Siene", GitHubUsername = "sienedekeyser", LastName = "Dekeyser", LinkedIn = "sienedekeyser", PhoneNumber = "0472040608" },
                        new { Id = new Guid("5fc97819-fe50-4b3c-a913-c089e1ab4f77"), Comment = "", Email = "luc.verhoeven@carglass.be", FirstName = "Luc", GitHubUsername = "lucverhoeven", LastName = "Verhoeven", LinkedIn = "lucverhoeven", PhoneNumber = "0472050403" }
                    );
                });

            modelBuilder.Entity("Swintake.domain.JobApplications.JobApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CampaignId");

                    b.Property<Guid>("CandidateId");

                    b.Property<string>("CurrentSelectionStepDescription");

                    b.Property<Guid?>("CurrentSelectionStepJobApplicationId");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("CurrentSelectionStepJobApplicationId", "CurrentSelectionStepDescription");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("Swintake.domain.JobApplications.SelectionSteps.SelectionStep", b =>
                {
                    b.Property<Guid>("JobApplicationId");

                    b.Property<string>("Description")
                        .HasMaxLength(90);

                    b.Property<string>("Comment")
                        .HasMaxLength(500);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("JobApplicationId", "Description");

                    b.ToTable("SelectionStep");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SelectionStep");
                });

            modelBuilder.Entity("Swintake.domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = new Guid("a79fac29-f3e2-4640-b686-97eb1bd62ae4"), Email = "reinout@switchfully.com", FirstName = "Reinout" },
                        new { Id = new Guid("d7590554-e931-4e2f-98ab-c223d94cdef2"), Email = "niels@switchfully.com", FirstName = "Niels" }
                    );
                });

            modelBuilder.Entity("Swintake.domain.JobApplications.SelectionSteps.CvScreening", b =>
                {
                    b.HasBaseType("Swintake.domain.JobApplications.SelectionSteps.SelectionStep");


                    b.ToTable("CvScreening");

                    b.HasDiscriminator().HasValue("CvScreening");
                });

            modelBuilder.Entity("Swintake.domain.JobApplications.SelectionSteps.FinalDecision", b =>
                {
                    b.HasBaseType("Swintake.domain.JobApplications.SelectionSteps.SelectionStep");


                    b.ToTable("FinalDecision");

                    b.HasDiscriminator().HasValue("FinalDecision");
                });

            modelBuilder.Entity("Swintake.domain.JobApplications.SelectionSteps.FirstInterview", b =>
                {
                    b.HasBaseType("Swintake.domain.JobApplications.SelectionSteps.SelectionStep");


                    b.ToTable("FirstInterview");

                    b.HasDiscriminator().HasValue("FirstInterview");
                });

            modelBuilder.Entity("Swintake.domain.JobApplications.SelectionSteps.GroupInterview", b =>
                {
                    b.HasBaseType("Swintake.domain.JobApplications.SelectionSteps.SelectionStep");


                    b.ToTable("GroupInterview");

                    b.HasDiscriminator().HasValue("GroupInterview");
                });

            modelBuilder.Entity("Swintake.domain.JobApplications.SelectionSteps.PhoneScreening", b =>
                {
                    b.HasBaseType("Swintake.domain.JobApplications.SelectionSteps.SelectionStep");


                    b.ToTable("PhoneScreening");

                    b.HasDiscriminator().HasValue("PhoneScreening");
                });

            modelBuilder.Entity("Swintake.domain.JobApplications.SelectionSteps.TestResult", b =>
                {
                    b.HasBaseType("Swintake.domain.JobApplications.SelectionSteps.SelectionStep");


                    b.ToTable("TestResult");

                    b.HasDiscriminator().HasValue("TestResult");
                });

            modelBuilder.Entity("Swintake.domain.JobApplications.JobApplication", b =>
                {
                    b.HasOne("Swintake.domain.Campaigns.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Swintake.domain.Candidates.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Swintake.domain.JobApplications.SelectionSteps.SelectionStep", "CurrentSelectionStep")
                        .WithMany()
                        .HasForeignKey("CurrentSelectionStepJobApplicationId", "CurrentSelectionStepDescription");
                });

            modelBuilder.Entity("Swintake.domain.JobApplications.SelectionSteps.SelectionStep", b =>
                {
                    b.HasOne("Swintake.domain.JobApplications.JobApplication", "JobApplication")
                        .WithMany("SelectionSteps")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Swintake.domain.Users.User", b =>
                {
                    b.OwnsOne("Swintake.domain.Users.UserSecurity", "UserSecurity", b1 =>
                        {
                            b1.Property<Guid?>("UserId");

                            b1.Property<string>("AppliedSalt")
                                .HasColumnName("AppliedSalt");

                            b1.Property<string>("PasswordHashedAndSalted")
                                .HasColumnName("PasswordHashed");

                            b1.ToTable("Users");

                            b1.HasOne("Swintake.domain.Users.User")
                                .WithOne("UserSecurity")
                                .HasForeignKey("Swintake.domain.Users.UserSecurity", "UserId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.HasData(
                                new { UserId = new Guid("a79fac29-f3e2-4640-b686-97eb1bd62ae4"), AppliedSalt = "NgBFEGiYlnKAVlAkBj6Qkg==", PasswordHashedAndSalted = "p1irTnDYNZBcCOfoph9UZaEmX5h4kd/UqkofgCUMMrA=" },
                                new { UserId = new Guid("d7590554-e931-4e2f-98ab-c223d94cdef2"), AppliedSalt = "rODZhnBsLGRP908sBZiXzg==", PasswordHashedAndSalted = "TeBgBijhTG1++pvIvcEOd0hvSGBE1Po1kh6TFlW097w=" }
                            );
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
